name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run unit tests
        run: npm test -- --coverage
      - name: Compile the application for production deployment
        run: npm run build
